-- MySQL Script generated by MySQL code

-- Author: James Chukwu


-- -----------------------------------------------------
-- Schema.sql
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `schema.sql` ;

-- -----------------------------------------------------
-- Schema code-buddy-db
-- -----------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Dumping database structure for schema.sql
CREATE DATABASE IF NOT EXISTS `schema.sql` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `schema.sql`;

-- Dumping structure for table schema.sql_developer_team
CREATE TABLE IF NOT EXISTS `developer-team` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `description` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

-- Dumping data for table generic.developer_team: ~5 rows (approximately)
/*!40000 ALTER TABLE `dveloper_team` DISABLE KEYS */;
INSERT INTO `developer_team` (`id`, `name`, `description`) VALUES
	(1, 'ceo', NULL),
	(2, 'admin', NULL),
	(3, 'Supervisor', NULL),
	(4, 'client', NULL),
	(5, 'Accountant', NULL);
/*!40000 ALTER TABLE `developer_team` ENABLE KEYS */;

--------Check the Age of Developer
-- -----------------------------------------------------
-- Before Insert Trigger for table `developer`
-- -----------------------------------------------------
DELIMITER $$
DROP TRIGGER IF EXISTS `age_check` $$
CREATE DEFINER = CURRENT_DEVELOPER TRIGGER `age_check` BEFORE INSERT ON `developer` FOR EACH ROW
BEGIN
DECLARE age INT UNSIGNED;
SELECT TIMESTAMPDIFF(YEAR, new.dob, CURDATE()) INTO age FROM DUAL;
----Develpoer must be above 15 year old
-----
    IF (age < 15) THEN
    SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'developer age_check constraint on developer.dob failed';
    END IF;
END$$
DELIMITER ;

--------

-- Dumping structure for table schema.sql-developer
CREATE TABLE IF NOT EXISTS `developer` (
  `id` int(1000) unsigned NOT NULL AUTO_INCREMENT,
  `first_name` varchar(50) DEFAULT NULL,
  `last_name` varchar(50) DEFAULT NULL,
  `email` varchar(50) NOT NULL,
  `password` varchar(200) NOT NULL,
  `dob` DATE NOT NULL,
  `driver_license_number` VARCHAR(12) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(12) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `driver_license_number_UNIQUE` (`driver_license_number` ASC),
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;

-- Dumping data for table schema.sql-developer: ~0 rows (approximately)
/*!40000 ALTER TABLE `developer` DISABLE KEYS */;

-- -------------------------- About 40 Developer are registered---------------------------
-- Data for table `developer`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `developer` (`id`, `first_name`, `last_name`, `dob`, `driver_license_number`, `email`, `phone`) VALUES (1, 'Mick', 'Showface', '1970-05-22', 'V435899293', 'mickshow0@yahoo.com', '713-441-2828');
INSERT INTO `developer` (`id`, `first_name`, `last_name`, `dob`, `driver_license_number`, `email`, `phone`) VALUES (2, 'Joseph', 'Bango', '1982-08-07', 'Z140530509', 'joebang1@gmail.com', '281-294-5458');
INSERT INTO `developer` (`id`, `first_name`, `last_name`, `dob`, `driver_license_number`, `email`, `phone`) VALUES (3, 'Luise', 'Pius',  '1971-03-10', 'W045654959', 'luipiu@yahoo.com', NULL);
INSERT INTO `developer` (`id`, `first_name`, `last_name`, `dob`, `driver_license_number`, `email`, `phone`) VALUES (4, 'Sospa', 'Evans', '1997-12-19', 'O232196823', 'ipacke4@cbc.ca', '157-815-8064');
INSERT INTO `developer` (`id`, `first_name`, `last_name`, `dob`, `driver_license_number`, `email`, `phone`) VALUES (5, 'Gabradi', 'Humphris', '1994-12-16', 'G055017319', 'khumphris5@xrea.com', '510-624-4189');
INSERT INTO `developer` (`id`, `first_name`, `last_name`, `dob`, `driver_license_number`, `email`, `phone`) VALUES (1, 'Moses', 'Danblocker', '1977-05-22', 'V435899293', 'mickshow0@yahoo.com', '713-441-2828');
INSERT INTO `developer` (`id`, `first_name`, `last_name`, `dob`, `driver_license_number`, `email`, `phone`) VALUES (2, 'Babalola', 'Sampson', '1986-08-07', 'Z140530509', 'joebang1@gmail.com', '281-294-5458');
INSERT INTO `developer` (`id`, `first_name`, `last_name`, `dob`, `driver_license_number`, `email`, `phone`) VALUES (3, 'Okechukwu', 'PiusMbonu',  '1981-03-10', 'W045654959', 'luipiu@yahoo.com', NULL);
INSERT INTO `developer` (`id`, `first_name`, `last_name`, `dob`, `driver_license_number`, `email`, `phone`) VALUES (4, 'Jerry', 'Nickolas', '1987-12-19', 'O232196823', 'jerrynicke4@yahoo.com', '281-815-8064');
INSERT INTO `developer` (`id`, `first_name`, `last_name`, `dob`, `driver_license_number`, `email`, `phone`) VALUES (5, 'Amanda', 'Casmire', '1984-12-16', 'G055017319', 'amanhris5@gmail.com', '713-624-4189');
INSERT INTO `developer` (`id`, `first_name`, `last_name`, `dob`, `driver_license_number`, `email`, `phone`) VALUES (1, 'Okorie', 'Tochukwu', '1970-05-22', 'V435899293', 'mickshow0@yahoo.com', '713-441-2828');
INSERT INTO `developer` (`id`, `first_name`, `last_name`, `dob`, `driver_license_number`, `email`, `phone`) VALUES (2, 'Makamba', 'Udorji', '1982-08-07', 'Z140530509', 'joebang1@gmail.com', '281-294-5458');
INSERT INTO `developer` (`id`, `first_name`, `last_name`, `dob`, `driver_license_number`, `email`, `phone`) VALUES (3, 'Silvester', 'Amadi',  '1971-03-10', 'W045654959', 'luipiu@yahoo.com', NULL);
INSERT INTO `developer` (`id`, `first_name`, `last_name`, `dob`, `driver_license_number`, `email`, `phone`) VALUES (4, 'Dominic', 'Umezuruike', '1997-12-19', 'O232196823', 'ipacke4@cbc.ca', '157-815-8064');
INSERT INTO `developer` (`id`, `first_name`, `last_name`, `dob`, `driver_license_number`, `email`, `phone`) VALUES (5, 'Gahndi', 'Mamugem', '1994-12-16', 'G055017319', 'gahumphris5@xrea.com', '510-624-4189');
INSERT INTO `developer` (`id`, `first_name`, `last_name`, `dob`, `driver_license_number`, `email`, `phone`) VALUES (1, 'Deborah', 'Damaniju', '1972-05-22', 'V435899293', 'moskshow0@yahoo.com', '713-441-2828');
INSERT INTO `developer` (`id`, `first_name`, `last_name`, `dob`, `driver_license_number`, `email`, `phone`) VALUES (2, 'Tinaalola', 'kampson', '1986-08-07', 'Z140530509', 'tinaseg1@gmail.com', '281-294-5458');
INSERT INTO `developer` (`id`, `first_name`, `last_name`, `dob`, `driver_license_number`, `email`, `phone`) VALUES (3, 'Bulekudo', 'Musbonu',  '1981-03-10', 'W045654959', 'okenipiu@yahoo.com', NULL);
INSERT INTO `developer` (`id`, `first_name`, `last_name`, `dob`, `driver_license_number`, `email`, `phone`) VALUES (4, 'Blany', 'Suckolas', '1997-12-19', 'O232196823', 'jerrynicke4@yahoo.com', '281-815-8064');
INSERT INTO `developer` (`id`, `first_name`, `last_name`, `dob`, `driver_license_number`, `email`, `phone`) VALUES (5, 'Tonanda', 'Shakime', '1985-12-16', 'G055017319', 'amanhris5@gmail.com', '713-624-4189');
INSERT INTO `developer` (`id`, `first_name`, `last_name`, `dob`, `driver_license_number`, `email`, `phone`) VALUES (1, 'Yakolufa', 'Mefajace', '1973-05-22', 'V435899293', 'yakokshow0@yahoo.com', '713-441-2828');
INSERT INTO `developer` (`id`, `first_name`, `last_name`, `dob`, `driver_license_number`, `email`, `phone`) VALUES (2, 'Pelosep', 'kolengo', '1984-08-07', 'Z140530509', 'poekang1@gmail.com', '281-294-5458');
INSERT INTO `developer` (`id`, `first_name`, `last_name`, `dob`, `driver_license_number`, `email`, `phone`) VALUES (3, 'Hajuise', 'bofus',  '1976-03-10', 'W045654959', 'haibiu@yahoo.com', NULL);
INSERT INTO `developer` (`id`, `first_name`, `last_name`, `dob`, `driver_license_number`, `email`, `phone`) VALUES (4, 'Tofupa', 'Medans', '1992-12-19', 'O232196823', 'macktofe4@cbc.ca', '157-815-8064');
INSERT INTO `developer` (`id`, `first_name`, `last_name`, `dob`, `driver_license_number`, `email`, `phone`) VALUES (5, 'Botabra', 'Fumaris', '1998-12-16', 'G055017319', 'boumfuris5@xrea.com', '510-624-4189');
INSERT INTO `developer` (`id`, `first_name`, `last_name`, `dob`, `driver_license_number`, `email`, `phone`) VALUES (1, 'lotoses', 'Ganbrolo', '1977-05-22', 'V435899293', 'ganlotosh0@yahoo.com', '713-441-2828');
INSERT INTO `developer` (`id`, `first_name`, `last_name`, `dob`, `driver_license_number`, `email`, `phone`) VALUES (2, 'Jamalob', 'Predampson', '1976-08-07', 'Z140530509', 'jompang1@gmail.com', '281-294-5458');
INSERT INTO `developer` (`id`, `first_name`, `last_name`, `dob`, `driver_license_number`, `email`, `phone`) VALUES (3, 'Kereukwu', 'Guoionu',  '1981-03-10', 'W045654959', 'Guipiu@yahoo.com', NULL);
INSERT INTO `developer` (`id`, `first_name`, `last_name`, `dob`, `driver_license_number`, `email`, `phone`) VALUES (4, 'Repoety', 'Macklolas', '1987-12-19', 'O232196823', 'rebymicke4@yahoo.com', '281-815-8064');
INSERT INTO `developer` (`id`, `first_name`, `last_name`, `dob`, `driver_license_number`, `email`, `phone`) VALUES (5, 'Kamanda', 'Sasmire', '1984-12-16', 'G055017319', 'kamasis5@gmail.com', '713-624-4189');
INSERT INTO `developer` (`id`, `first_name`, `last_name`, `dob`, `driver_license_number`, `email`, `phone`) VALUES (1, 'Ojobie', 'Yobuku', '1970-05-22', 'V435899293', 'oyicksow0@yahoo.com', '713-441-2828');
INSERT INTO `developer` (`id`, `first_name`, `last_name`, `dob`, `driver_license_number`, `email`, `phone`) VALUES (2, 'Totalamba', 'Morji', '1982-08-07', 'Z140530509', 'joebang1@gmail.com', '281-294-5458');
INSERT INTO `developer` (`id`, `first_name`, `last_name`, `dob`, `driver_license_number`, `email`, `phone`) VALUES (3, 'Dilmitaso', 'Kalmadi',  '1975-03-10', 'W045654959', 'dipiku@yahoo.com', NULL);
INSERT INTO `developer` (`id`, `first_name`, `last_name`, `dob`, `driver_license_number`, `email`, `phone`) VALUES (4, 'Somanic', 'Demezuru', '1997-12-19', 'O232196823', 'denacke4@cbc.ca', '157-815-8064');
INSERT INTO `developer` (`id`, `first_name`, `last_name`, `dob`, `driver_license_number`, `email`, `phone`) VALUES (5, 'Gohendi', 'Tamukem', '1994-12-16', 'G055017319', 'gotumphris5@xrea.com', '510-624-4189');
INSERT INTO `developer` (`id`, `first_name`, `last_name`, `dob`, `driver_license_number`, `email`, `phone`) VALUES (1, 'Bebosah', 'Pananiku', '1979-05-22', 'V435899293', 'moskshow0@yahoo.com', '713-441-2828');
INSERT INTO `developer` (`id`, `first_name`, `last_name`, `dob`, `driver_license_number`, `email`, `phone`) VALUES (2, 'Kilaloma', 'Fambson', '1988-08-07', 'Z140530509', 'kifaseg1@gmail.com', '281-294-5458');
INSERT INTO `developer` (`id`, `first_name`, `last_name`, `dob`, `driver_license_number`, `email`, `phone`) VALUES (3, 'Ruvekado', 'Duhonu',  '1984-03-10', 'W045654959', 'renopiu@yahoo.com', NULL);
INSERT INTO `developer` (`id`, `first_name`, `last_name`, `dob`, `driver_license_number`, `email`, `phone`) VALUES (4, 'Redalany', 'Rukelas', '1998-12-19', 'O232196823', 'redyricke4@yahoo.com', '281-815-8064');
INSERT INTO `developer` (`id`, `first_name`, `last_name`, `dob`, `driver_license_number`, `email`, `phone`) VALUES (5, 'Fokando', 'Makime', '1995-12-16', 'G055017319', 'famamris5@gmail.com', '713-624-4189');
COMMIT;

/*!40000 ALTER TABLE `users` ENABLE KEYS */;



-- Dumping structure for table schema.sql-coding_language
CREATE TABLE IF NOT EXISTS `coding_language` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `shortcode` varchar(2) DEFAULT NULL,
  `full` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `shortcode` (`shortcode`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;

-- Dumping data for table schema.sql-coding_language: ~0 rows (approximately)
/*!40000 ALTER TABLE `coding-language` DISABLE KEYS */;
INSERT INTO `coding_language` (`id`, `shortcode`, `full`) VALUES
	(1, 'JS', 'Javascript'),
	(2, 'API', NULL),
	(3, 'HTML', 'Index.html'),
	(4, 'PT', 'Python'),
	(5, 'BT', 'Bootstrap'),
	(6, 'NJ', 'Node.js'),
	(7, 'DB', 'Schema.sql'),
	(8, 'CSS', 'Style.css'),
	(9, 'RM', 'Readme.md');
/*!40000 ALTER TABLE `coding_language` ENABLE KEYS */;



-- Dumping structure for table schema.sql_notifications
CREATE TABLE IF NOT EXISTS `notifications` (
  `id` int(1) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `body` varchar(250) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Dumping data for table schema.sql_notifications: ~0 rows (approximately)
/*!40000 ALTER TABLE `notifications` DISABLE KEYS */;
/*!40000 ALTER TABLE `notifications` ENABLE KEYS */;


